<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Home' =>'主页',
	'Authenticate'=>'权限管理',
	'Configs' => '基础配置',
	'Create Config' => '添加配置信息',
	'Update'=>'更新',
	'Delete'=>'删除',
	'Create'=>'添加',
	'Success'=>'成功',
	'Are you sure you want to delete this item?'=>'确定删除？',
	'Index'=>'列表页',
	'Details'=>'详情',
	'Backend'=>'后台管理',
	'Update {modelClass}: '=>'修改 {modelClass}：',
	'Please fill out the following fields to login:'=>'请输入登入信息：',
	'Login'=>'登入',
	'Logout'=>'退出',
	'User Name'=>'用户名',
	'Password'=>'密码',
	'Verify Code'=>'验证码',
	'Remember Me'=>'记得密码',
	'Adminstrator'=>'管理员',
	'Users'=>'用户',
	'Create User'=>'添加用户',
	'Action'=>'操作',
	'Muest One Super Manager'=>'必须有一个超级管理员',
	'User manager'=>'用户管理',
	'Memeber' =>'会员',
	'Logininfos'=>'管理员',
	'Create Logininfo'=>'添加管理员',
	'Goods'=>'产品管理',
	'Category'=>'分类信息',
	'CMS'=>'文章管理',
	'Page'=>'页面信息',
	'Tag'=>'标签信息',
	'Feature'=>'特征信息',
	'Feature Attribute'=>'特征属性',
	'AuthRole'=>'权限角色',
	'AuthItem'=>'权限项目',
	'AuthRule'=>'权限规则',
	'page'=>'页面',
	'product'=>'产品',
	'list'=>'列表',
	'Tags'=>'标签',
	'Create Tag'=>'添加标签',
	'Categories'=>'分类信息',
	'Features'=>'产品特征',
	'Attribute'=>'属性',
	'Images'=>'图片管理',
	'Upfiles'=>'文件管理',
	'File'=>'文件',
	'Order'=>'排序',
	'Pages'=>'页面',
	'Price'=>'单价',
	'Quanity'=>'数量',
	'Congratulations!'=>'欢迎！',
	'Order Manager'=>'订单管理',
	'View All'=>'查看全部',
	'Languages'=>'语言',
	'Extension'=>'扩展',
	'Extensions'=>'扩展',
	'Slider'=>'轮播',
	'Payment'=>'支付',
	'images'=>'图组',
	'Url'=>'连接',
	'Options'=>'配置',
	'Key'=>'关键标识',
	'Value'=>'值',
	'Prev Level'=>'上一级',
	'Sku No.'=>'編號',
	'Goods Category'=>'产品类目',
	'Group'=>'特征组',
	'Label Name'=>'标签名称',
	'Group ID More than two'=>'特征组的特征大于2个',
	'Goods extensions error'=>'产品扩展信息出错',
	'Next'=>'下一步',
	'Modify Goods Category'=>'修改产品类目',
	'Modify'=>'修改',
	'Please choose'=>'請選擇',
	'Upload'=>'上傳',
	'Currency'=>'货币',
	'Product'=>'产品',
	'Shipment PostCode'=>'运费邮编',
	'Shipment Postcode'=>'运费邮编',
	'Coupon'=>'优惠',
];
