<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Configs' => '基础配置',
	'Create Config' => '添加配置信息',
	'Update'=>'更新',
	'Delete'=>'删除',
	'Create'=>'添加',
	'Success'=>'成功',
	'Are you sure you want to delete this item?'=>'确定删除？',
	'Index'=>'列表页',
	'In Backlist'=>'加入黑名單',
	'Details'=>'详情',
	'Backend'=>'后台管理',
	'Order ID'=>'排序',
	'Status'=>'状态',
	'Key'=>'关键标识',
	'Url'=>'外连接',
	'show'=>'是否显示',
	'nav'=>'导航显示',
	'footer'=>'页尾显示',
	'side'=>'侧边显示',
	'Language'=>'语言',
	'Sales'=>'销售',
	'Attributes'=>'扩展',
	'Attributes Name'=>'扩展名',
	'Attributes Value'=>'扩展值',
	'Add Attributes'=>'添加属性：',
	'Tag'=>'分类标签',
	'Options'=>'配置',
	'Name'=>'名称',
	'Product Id'=>'产品ID',
	'Alias'=>'命名',
	'Feature'=>'特征分类',
	'Group'=>'分组',
	'Options Value'=>'属性值',
	'Group ID'=>'分组ID',
	'Currency Code'=>'货币代码',
	'Currency Value'=>'货币汇率',
	'Currency'=>'货币符号',
	'Modifydate'=>'修改时间',
	'Postcode'=>'邮编',
	'Price'=>'费用',
	'Add Options'=>'添加选项',
	'Coup ID'=>'优惠券ID',
	'Coup No'=>'优惠券码',
	'Type'=>'类型',
	'Coup Value'=>'优惠券值',
	'Coup Quanity'=>'优惠券数量',
	'Start Date'=>'开始日期',
	'End Date'=>'结束时间',
	'Flat Date'=>'是否以星期为主',
	'Flat Coup'=>'优惠券类型',
	'coupons'=>'优惠',
	'discount'=>'打折',
	'Up FREE'=>'满就送',
	'FREE Shipment'=>'满就包邮',
];
