<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'ID' => '编号',
	'Options' => '配置',
	'Values' => '值',
	'Status'=>'状态',
	'Login ip' => '登入IP',
	'Modify time' => '最后一次修改时间',
	'Add time' => '添加时间',
	'Freezing'=>'冻结',
	'Money' => '金额',
	'Points' => '积分',
	'Power' => '权限',
	'Phone'=>'电话',
	'E-mail'=>'邮箱',
	'Password' => '密码',
	'User name' => '用户名',
	'Login time'=>'登入时间',
	'files'=>'文件',
	'Extension Options'=>'扩展选项',
	'Extension Attributes'=>'扩展属性',
	'Categories Specifications'=>'分类规格',
	'Goods Category'=>'产品分类',
	'Extension Infomations'=>'扩展信息',
	'Base Infomations'=>'基本信息',
	'Group Options'=>'分组选项',
	'Goods Infomations'=>'产品信息',
	'discount'=>'折扣',
	'subtract'=>'减',
	'FREE'=>'免费',
	'Order ID'=>'订单ID',
];
