wowReInitor(jQuery("#wowslider-container1"), {
    effectsPath:"./frontend/web/js/effect/",
    effect: "blur",
    prev: "",
    next: "",
    duration: 19 * 100,
    delay: 29 * 100,
    width: 960,
    height: 360,
    autoPlay: true,
    playPause: true,
    stopOnHover: false,
    loop: false,
    bullets: true,
    caption: true,
    captionEffect: "move",
    controls: true,
    onBeforeStep: 0,
    images: 0
});