<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Add New Address'=>'新增收貨地址',
	'Amount:'=>'結算金額：',
	'Continue shopping'=>'繼續購物',
	'Confirm'=>'確認',
	'Order'=>'訂單',
	'Delete the selected'=>'刪除選擇的商品',
	'Next' => '下一步',
	'Step 1：Shopping Cart' => '第一步：已購買商品',
	'Step 2：Account & Billing Details' => '第二步：賬戶賬單信息',
	'Step 3：Shipment Method'=>'第三步：貨運方式',
	'Step 4：Payment Method' => '第四步：付款方式',
	'Step 5：Confirm Order' => '第五步：確認訂單',
	'Goods Informations'=>'商品信息',
	'Payment Method'=>'付款方式',
	'Confirm Order'=>'確認訂單',
	'Please select the preferred shipment method to use on this order.'=>'請選擇訂單運輸方式。',
	'Please select the preferred payment method to use on this order.'=>'請選擇支付方式。',
	'Payment Total:'=>'支付總價',
	'Receiver'=>'收貨人',
	'Receiver Phone'=>'收貨人電話',
	'Shipping:'=>'運費：',
	'Shipping address'=>'收貨地址',
	'Total'=>'合計',
	'Total amount of goods:'=>'商品總額：',
	'Order Total:'=>'訂單總額：',
	'Modify'=>'修改',
];
