<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Configs' => '基礎配置',
	'Create Config' => '添加配置信息',
	'Cancel Order'=>'取消訂單',
	'Update'=>'更新',
	'Delete'=>'刪除',
	'Create'=>'添加',
	'Success'=>'成功',
	'Are you sure you want to delete this item?'=>'確定刪除？',
	'Index'=>'列表頁',
	'Details'=>'詳情',
	'Backend'=>'後臺管理',
	'Order ID'=>'排序',
	'Status'=>'狀態',
	'Key'=>'關鍵標識',
	'Url'=>'外連接',
	'show'=>'是否顯示',
	'nav'=>'導航顯示',
	'footer'=>'頁尾顯示',
	'side'=>'側邊顯示',
	'Language'=>'語言',
	'Sales'=>'銷售',
	'Attributes'=>'擴展',
	'Attributes Name'=>'擴展名',
	'Attributes Value'=>'擴展值',
	'Add Attributes'=>'添加屬性：',
	'Tag'=>'分類標簽',
	'Options'=>'配置',
	'Order Pay'=>'立刻支付',
	'Name'=>'名稱',
	'Product Id'=>'產品ID',
	'Pending'=>'下單',
	'Completed'=>'已支付',
	'Shipped'=>'已發貨',
	'Confirm'=>'確認收貨',
	'Server'=>'售後服務',
	'Refunded'=>'退貨',
	'Cancel'=>'取消',
];
