<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'ID' => '編號',
	'Options' => '配置',
	'Values' => '值',
	'Status'=>'狀態',
	'Login ip' => '登入IP',
	'Modify time' => '最後壹次修改時間',
	'Add time' => '添加時間',
	'Freezing'=>'凍結',
	'Money' => '金額',
	'Points' => '積分',
	'Power' => '權限',
	'Phone'=>'電話',
	'E-mail'=>'郵箱',
	'Password' => '密碼',
	'User name' => '用戶名',
	'Login time'=>'登入時間',
];
